edition = "2021"
fn_params_layout = "Vertical"
force_explicit_abi = true
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_try_shorthand = true
